name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Validate composer.json, composer.lock
        run: make composer-validate

      - name: Build
        run: make build

      - name: Lint
        run: make phpcs

      - name: Test
        run: make phpunit