name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Lint
        run: make lint

      - name: Build
        run: make build

#      - name: Test
#        run: make test