name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          php: [7.4, 7.3, 7.2]
          laravel: [7.*, 6.*, 5.8.*]
          include:
              -   laravel: 7.*
                  testbench: 5.*
              -   laravel: 6.*
                  testbench: 4.*
              -   laravel: 5.8.*
                  testbench: 3.8.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Validate composer.json
        run: make composer-validate

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
            coverage: none

      - name: Install dependencies
        run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "symfony/console:>=4.3.4" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-suggest

      - name: Run linting
        run: vendor/bin/phpcs

      - name: Run tests
        run: vendor/bin/phpunit
