name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3, 7.2]
        laravel: [7.*, 6.*, 5.8.*]
        include:
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*
          - laravel: 5.8.*
            testbench: 3.8.*
          - php: 7.4
            mockery: 1.4.*
          - php: 7.3
            mockery: 1.4.*
          - php: 7.2
            mockery: 1.3.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Validate composer.json
        run: make composer-validate

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/laravel:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "mockery/mockery:${{ matrix.mockery }}" "symfony/console:>=4.3.4" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Run linting
        run: vendor/bin/phpcs

      - name: Run tests
        run: make phpunit-coverage-clover

  coverage:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/laravel:7.*" "orchestra/testbench:5.*" "mockery/mockery:1.4" "symfony/console:>=4.3.4" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Coverage
        run: make phpunit-coverage-clover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
